---
title: "DATA 605 - Homework 10"
author: "Omer Ozeren"
output:
  word_document:
    toc: yes
    toc_depth: '3'
  html_document:
    highlight: tango
    theme: journal
    toc: yes
    toc_depth: 5
    toc_float: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Question 1
Smith is in jail and has 1 dollar; he can get out on bail if he has 8 dollars.
A guard agrees to make a series of bets with him. If Smith bets A dollars,
he wins A dollars with probability .4 and loses A dollars with probability .6.
Find the probability that he wins 8 dollars before losing all of his money if

### (a) he bets 1 dollar each time (timid strategy).

### (b) he bets, each time, as much as possible but not more than necessary to bring his fortune up to 8 dollars (bold strategy).

### (c) Which strategy gives Smith the better chance of getting out of jail?

# Solutions

This is known as the Gambler's Ruin problem. 

We are given:

Initial stake $z = k = 1$.

$M = 8$

$P = 0.4$

$q = 0.6$

$q_z = \frac{(\frac{q}{p})^z - 1}{(\frac{q}{p})^M - 1}$

## (a) 

$q_z = \frac{(\frac{0.6}{0.4})^1 - 1}{(\frac{0.6}{0.4})^8 - 1} =$ `r (0.6/0.4 - 1)/((0.6/0.4)^8 - 1)`.

There is a ~2% probability Smith will win using this strategy.

## (b)

The quickest strategy is if he bets everything each time. That is, beginning from state $z = k = 1$, he can move fall to 0 with $q = 0.6$, or rise to 2 with $p = 0.4$. Similarly, suppose he moved to 2, he bets everything, and can fall to 0 with $q = 0.6$, or rise to 4 with $p = 0.4$.


Using the formula $q_k = p\cdot q_{k+1} + q\cdot q{k-1}$:

$q_0 = 0$

$q_1 = (0.4)q_2 + (0.6)q_0$

$q_2 = (0.4)q_4 + (0.6)q_0$

$q_4 = (0.4)q_8 + (0.6)q_0$

$q_8 = 1$

$(0.4)^3 =$ `r (0.4)^3`.

## (C)
Interestingly even starting with $6, the probability of getting out of jail is not on Smith's side.

Neither strategy gives you particulary good chance of getting out of jail. However, bold strategy is noticeably better than timid strategy (1 in 15 chance vs. 1 in 50 chance).