---
title: "DATA 605 - Discussion 13"
author: "Omer Ozeren"
output:
  html_document:
    highlight: tango
    theme: journal
    toc: yes
    toc_depth: 5
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '3'
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

## Chapter 7 Sec 4 Exercise 5

Find the arc length of the function on the given interval.

$f(x) = \frac{1}{3}x^{\frac{3}{2}}-x^{\frac{1}{2}}$ on $[0,1]$

### Define Function

```{r}
func <- function(x) 1/3 * x^(3/2) - x^(1/2)
```

### Plot

```{r}
x <- seq(0,1,0.01)
plot(x,func(x), type="l",
     xlab="x", ylab="f(x)", main="f(x) on [0,1]")
```

### Solution

$f'(x) = \frac{1}{3}\times \frac{3}{2}x^{\frac{1}{2}}-\frac{1}{2}x^{-\frac{1}{2}} = \frac{\sqrt{x}}{2} - \frac{1}{2\sqrt{x}} = \frac{x-1}{2\sqrt{x}}$

$$
\begin{split}
L_{arc} &= \int_0^1 \sqrt{1+f'(x)^2} dx =\\
&=  \int_0^1 \sqrt{1+\frac{(x-1)^2}{4x}} dx = \\
&=  \int_0^1 \sqrt{\frac{4x+x^2-2x+1}{4x}} dx = \\
&=  \int_0^1 \sqrt{\frac{x^2+2x+1}{4x}} dx = \\
&=  \int_0^1 \sqrt{\frac{(x+1)^2}{4x}} dx = \\
&=  \int_0^1 \frac{x+1}{2\sqrt{x}} dx = \\
&= \frac{4}{3} \approx 1.333
\end{split}
$$
